name: test
description: A test app for lyacc!
version: 1.0.0
homepage: https://github.com/iamtheblackunicorn/lyacc
publish_to: none
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  lyacc:
    git: git://github.com/iamtheblackunicorn/lyacc.git
