name: lyacc
description: An over-powered engine to make language development in Dart easier. Your rules. Your language.
version: 1.0.1-nullsafety.0
homepage: https://github.com/iamtheblackunicorn/lyacc
environment:
  sdk: '>=2.12.0 <3.0.0'
dependencies:
  pedantic: ^1.11.0
